# このファイルはテスト先のGitLabでCI/CDするためのものです。
#
stages:
  - py38test
  - py39test

py38test_job:
  script:
    - python3.8 test.py
  tags:
    - gpurunner

py39test_job:
  script:
    - python3.9 test.py
  tags:
    - gpurunner
